const Discord = require("discord.js");
exports.run = (client, message, args) => {
message.channel.sendMessage("**Vac**ation"),
message.edit("===========================  :red_car: "),
message.edit("==========================  :red_car: "),
message.edit("=========================  :red_car: "),
message.edit("========================  :red_car: "),
message.edit("======================  :red_car: "),
message.edit("=====================  :red_car: "),
message.edit(":warning: **Traffic** :warning: "),
message.edit("=======================  :red_car: "),
message.edit("======================  :red_car: "),
message.edit("=====================  :red_car: "),
message.edit("====================  :red_car: "),
message.edit("===================  :red_car: "),
message.edit("==================  :red_car: "),
message.edit("=================  :red_car: "),
message.edit("================  :red_car: "),
message.edit("===============  :red_car: "),
message.edit("==============  :red_car: "),
message.edit("=============  :red_car: "),
message.edit("============  :red_car: "),
message.edit("===========  :red_car: "),
message.edit("==========  :red_car: "),
message.edit("=========  :red_car: "),
message.edit("========  :red_car: "),
message.edit("=======  :red_car: "),
message.edit("======  :red_car: "),
message.edit("=====  :red_car: "),
message.edit("====  :red_car: "),
message.edit("===  :red_car: "),
message.edit("==  :red_car: "),
message.edit("=  :red_car: "),
message.edit(" :red_car: "),
message.edit("**Vac**ation over")
};